# See: https://docs.gitlab.com/ce/ci/yaml/README.html
cache:
    paths:
        - vendor/

variables:
    FF_USE_FASTZIP: "true"
    ARTIFACT_COMPRESSION_LEVEL: "fast"
    CACHE_COMPRESSION_LEVEL: "fast"
    PHP_BIN_DEFAULT: php7.4

.parallel-php-versions:
    parallel:
        matrix:
            - PHP_BIN: [ php7.4 ]

composer:
    script:
        - $PHP_BIN_DEFAULT /usr/local/bin/composer install --no-progress

tests:
    extends: .parallel-php-versions
    script:
        # Run unit tests with phpunit
        - $PHP_BIN vendor/bin/phpunit --colors=never --coverage-text --coverage-cobertura=coverage.cobertura.xml --log-junit report.xml
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.cobertura.xml
            junit: report.xml
    needs: ["composer"]

phpstan:
    script:
        - $PHP_BIN_DEFAULT vendor/bin/phpstan analyze --no-progress
    needs: ["composer"]

phpcs:
    script:
        - $PHP_BIN_DEFAULT vendor/bin/phpcs
    needs: ["composer"]

php-cs-fixer:
    script:
        - $PHP_BIN_DEFAULT vendor/bin/php-cs-fixer fix -vv --dry-run --stop-on-violation
    needs: ["composer"]

#satis:
#    stage: deploy
#    script:
#        - cd /data/sites/dp-satis; php7.3 -dmemory_limit=2048M bin/satis build --repository-url git@gitlab.com:EspaceProprio/duproprio/php-project-skeleton.git satis.json public_html
